name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: ./.github/workflows/setup-rust
      - run: cargo build --release
      - run: exit 1 # Force a failure to test cache-on-failure
